#!/usr/bin/env node
'use strict'

const fs = require('fs')
const path = require('path')
const cheerio = require('cheerio')

var argv = process.argv.slice(2)
const template = argv.shift()
const source_dir = argv.shift()

const html = fs.readFileSync(template, 'utf8')
const $ = cheerio.load(html)

const ext = '.html'

const query = '[data-fill]'
var elements = $(query)

for (var i = 0; i < elements.length; i++) {
	var piece_name = $(elements[i]).data('fill')
	var file = path.join(source_dir, piece_name + ext)
	var piece = fs.readFileSync(file).toString()
	$(elements[i]).append(piece)
}

console.log($.html())
